### ISSUE TITLE
[Feature Request] Disable/Enable button groups and buttons

### ISSUE THREAD

**Issue by kdumovic** [folivoraAI/BetterTouchTool#1028]
It would be nice to have an option to disable or enable button groups and/or buttons from appearing in the global touch bar UI.

This could be similar to how Alfred allows you to disable and enable workflows.

Right now the only way to prevent a button from appearing is to delete it. But if you've spent some time configuring it (adding an icon, writing an apple script, playing with settings) you don't want your hard work to disappear. Adding the option to disable that button or group and keep it from appearing allows you to save your work for later and keeps you more flexibility in customizing and experimenting with the global touch bar layout. 

--

A related feature would be the ability to export a button group to a file or folder so that you can share it with others! Would be awesome to see community-contributed button group widgets and control layouts.

**Comment by brockgr** [comment]
+1 Yup my use case would be to have a button group appear if I have a youtube video open in chrome. I can detect this using applescript, and then would show a button to open a buttongroup with play/pause and title widgets. (I would rather not have this group open all the time, since I may be in another app.
