### ISSUE TITLE
Keyboard and Trackpad Freeze

### ISSUE THREAD

**Issue by saiahlee** [folivoraAI/BetterTouchTool#1032]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
After I updated BTT v.2.10 my built-in keyboard and trackpad are frequently frozen earlier (once I pluged out external keyboard and mouse), and later they're just permanently frozen. I had to use external keyboard and mouse.
I updated BTT v.2.20 yesterday, and it seemed everything is fixed. However, the problem started again. Now my built-in keyboard and trackpad don't work. I have to use external keyboard and mouse.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook built-in Keyboard and Trackpad

#### Device information:

Type of Mac: MacBook Pro (Retina, 13-inch, Early 2015)
macOS version: macOS Sierra (Version 10.12.5)
BetterTouchTool version: BetterTouchTool v2.20 (641)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
I use external wireless usb keyboard and mouse made by Microsoft. (Sculpt Ergonomic Desktop)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by saiahlee** [comment]
I think this is not fixed in Alpha Version 2.21 (642). Thanks!

**Comment by fifafu** [comment]
Sorry, but I can't reproduce this and haven't had any similar reports yet. I think this might be caused by something else or by a conflict with some other software.

Maybe try to reset your BetterTouchTool settings completely. 

You can delete all BTT settings using these two terminal commands (while BTT is quit): 

defaults delete com.hegenberg.BetterTouchTool 

rm -r ~/Library/Application Support/BetterTouchTool

**Comment by saiahlee** [comment]
Thank you for your hard working! I think the problem was my own, not the BTT. Now I fixed the problem. I'm sorry for bothering you! :)

**Comment by udondan** [comment]
Since a couple of days my Mac freezes for ~20 seconds whenever I change the active window. No mouse or keyboard input shows any reaction. Both external BT and internal MBP. It took me quite some time to figure out that this is caused by or at least related to BTT:

- Killing random process
- Change window
- Freeze ~20 seconds
- Switch to Activity Monitor
- Freeze ~20 seconds
- Kill random process
- ...

Twice now the problem was immediately gone after killing BTT. I haven't made any config changes.

@saiahlee What was the cause for this issue on your Mac?

**Comment by udondan** [comment]
Leaving backlink here: https://community.folivora.ai/t/macos-10-13-4-freezing-with-bettertouchtool-usage/1185
