### ISSUE TITLE
Icon for Touchbar button appears as white square in the Touchbar but is correctly displayed within BTT

### ISSUE THREAD

**Issue by RichardTsc** [folivoraAI/BetterTouchTool#1034]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

When I add [this](http://rysk.eu/Textbox.png) icon to a Touchbar button within BTT, it is correctly previewed within BTT but on the Touchbar, it only appears as white square (see [here](http://rysk.eu/TouchBarBug.png))

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 2.20 (641)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
In order to support black icons on the touchbar BTT uses so called "template" images. The system automatically changes the color of those icons to fit in the Touch Bar. This is done by using the non-transparent pixels of an image as a mask.

For colored icons BTT automatically disables this behavior, however your icon is completely greyscale thus BTT assumes it's a "template" icon. 
Unfortunately there is currently no way to disable this behavior but maybe I can somehow make it configurable in the future.

For now the only solution would be to add a non greyscale pixel to the icon.

**Comment by RichardTsc** [comment]
Great, that already helps a lot to understand the behaviour! How is "non greyscale" defined? A pixel where not(r=b=g)? So e.g., 255, 255, 254?

**Comment by MostlyAbsent** [comment]
I worked on the top left pixel, d3d3d3 in colour. I had to bring it to d3d3b4 before it showed up normally.
