### ISSUE TITLE
Touchbar FN Function Keys

### ISSUE THREAD

**Issue by rscosworth** [folivoraAI/BetterTouchTool#1097]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Just getting started with Better Touch Tool, I have a single app which I would like to always display the FN keys when the app is at the front, without having to touch anything else, and I would not like to have to press the FN key before the F1 etc are displayed.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: 2017 MacBook Pro Touch
macOS version: 10:12:5
BetterTouchTool version: 2.21 (641)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by Vrolijkx** [comment]
@rscosworth You can configure this in ```System Preferences > Keyboard > Shortcuts```
Choose Function Keys and add you application. 
But it would be nice if we could toggle this Fn bar from BTT because now it's an all or nothing switch. As a programmer, I use my Fn keys a lot in shortcuts. But I also would like to use the BTT touch bar customization for adding debugging and refactoring actions. It would be nice if there was an ```Fn``` widget which when pressed shows the Function keys. And on pressing ```esc``` you would jump back to you basic touch bar. @fifafu what do you think?

**Comment by rscosworth** [comment]
I've worked around it by making new function key buttons and assigning them to the shift key switch.

I was having an issue with F4 and F11 keys as they were returning the Mac shortcuts, f11 was easily disabled but no idea what F4 is meant to do.

I can't assign the application to show function keys as it's a java app, which means I also can't assign my new function keys on BTT because of the same issue. Hence having to use the shift switch.

Ideally java support in BTT would resolve my issues I believe!

**Comment by lennartcl** [comment]
Related: FN keys you add to the touch bar yourself don't work with modifiers (https://github.com/fifafu/BetterTouchTool/issues/236)
