### ISSUE TITLE
customizable menu

### ISSUE THREAD

**Issue by joernhees** [folivoraAI/BetterTouchTool#1121]
Thanks for the awesome tool, i've been a happy user for years.

With the recent announcement that you added a clipboard history, i realized that i was unaware of tons of cool features you added over time. I think one cool feature would be to have a customizable "BetterTouchTool Menu" that is reachable via the dock item. It could by default just show all of the "Predefined Actions":
<img width="383" alt="image" src="https://user-images.githubusercontent.com/464192/27547745-2d4cb816-5a97-11e7-872e-dd199b15880d.png">

In your preferences you could have another tab to customize that menu (checkboxes in front to activate / deactivate items, allow moving them around, etc.), maybe even define multiple ones and trigger them as overlay via any of the triggers etc.

Tree-like / radial #1100 don't really care ;)

**Comment by fifafu** [comment]
I'm not sure if it would be a good idea to show all of the actions, because most of them don't really work just by selecting them from a menu.

However you can already create your own menu with a little trick, just define one gesture/shortcut multiple times and assign different actions, like in this screenshot:

![image](https://user-images.githubusercontent.com/8820811/27561637-330ffd30-5ac9-11e7-80a6-ed74ac594b10.png)


I could definitely improve this though :-)

**Comment by joernhees** [comment]
heh, cool, didn't know that either...

As you see this is mostly about "discoverability" of your features.

I think if you made the dock icon more useful (maybe even allow customizing it), users would use it and you'd have a perfect place to show new features.

The customizable menus could be part of that / the dock could be one of the customizable windows into which you add new features that by default are activated ;)

**Comment by DCNielsen** [comment]
I like this selection menu that appears when you make two shortcuts for the same thing. That's a great feature. I wish it could be laid out in a 3x3 or radial grid of icons. Amazing if it could also appear by mouse press and trigger by mouse release. That's sort of my previous request. 

I feel like it meets multiple requests - it's obliquely scratching the itch to trigger things with a straight line gesture at the same time. Any thoughts toward that? Love BTT by the way.

**Comment by SynerG** [comment]
I also like being able to create your own menus. It allows to have important actions right at the cursor, without having to memorize them by heart (as it happens with gestures or keyboard shortcuts). In some cases, the menu is a better choice.

The little trick commented by @fifafu is also good to realize that you have defined the same trigger twice.

However, using the trick as the main mechanism to define menus is not as great as others options in BTT:
- You have to redefined the same trigger many times which is slow. Also, if you want to change the trigger, you have to change it multiple times.
- In order to define a submenu, you have to artificially define a shortcut not used yet in that context, only to again define it as the trigger of each action of the submenu

A more straighforward way of defining personalized menus would be awesome.

To be able to invoke options of the menu fast, I also prefer the Radial Menu proposal as all the options are equally close to the current cursor position, it is easy to land on them and your muscles can learn to do it automatically without looking. On the other side, regular menus allow a longer list of options and with longer text strings on each one :)
