### ISSUE TITLE
[FR] Touchbar Application List

### ISSUE THREAD

**Issue by niklasfink** [folivoraAI/BetterTouchTool#1192]
#### Feature Request: Touchbar Application List

Hi, I'd like to request the feature to have a list of applications in the Touchbar which always stays the same. This would be different from the current (v2.266) implementation of the App Switcher widget, which works similar to the command+tab function (and changes App icon positions).

Configuration of this function works via a list of all applications where a user can tick the apps which should be shown on the Touchbar. Once saved, it should look similar to the App Switcher but without Apps changing their position.

Another way, for easier implementation, would be a way to use an Application Icon as the Icon of a Touchbar button (which would be a good feature anyway) and being able to disable the light grey border. This would give a user a way to create App lists and having a similar look and feel as the App Switcher widget.

**Comment by callodacity** [comment]
So are you looking for something like a Dock in the Touch Bar?

---

Also, since you can change the background of Touch Bar buttons, have you tried setting it to `#000000` or all black?
Setting it to black and putting an application icon there seems to be exactly what you're looking for. You could also set the padding to `0` or even a negative value to shrink the button size.

As a quick Proof of Concept take a look at my application icon on the far right - there's not button behind it.
<img width="1085" alt="touch bar shot 2017-08-29 at 4 29 26 pm" src="https://user-images.githubusercontent.com/1011648/29807418-45fbd7f8-8cd7-11e7-8127-6353d2e73768.png">
