### ISSUE TITLE
false trigger with force trackpad

### ISSUE THREAD

**Issue by stemuser** [folivoraAI/BetterTouchTool#1328]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Hi, I'm using a new MacBook Pro with force trackpad.   the "one finger tap" is turned on in system preference-trackpad, there is false trigger after some gestures (e.g. "3 finger click")  ,  this didn't happen on my old macbook with old trackpad. 
when the "one finger tap" is turned off in system preference-trackpad, there is no false trigger.
 Is there any way to solve this issue without turning off "one finger tap"?  (like "delay one-finger-tap for 0.5s after certain gesture in BTT")

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

new MacBook Pro with force trackpad.

#### Device information:

Type of Mac: MacBook Pro 2017 with force trackpad.
macOS version: 10.12.6
BetterTouchTool version: 2.281

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by dabrahams** [comment]
This is very closely related to a problem I have where "tap-to-click" and also general mouse movement gets triggered during typing due to palms brushing the trackpad while typing.  This is actually a very widespread problem (google: "2016" "macbook pro" "tap to click" palm rejection) that BTT comes tantalizingly close to addressing with options like "Disable trackpad gestures after hitting a keyboard key" and "Thumb/palm handling" and "required pressure for 3 and 4 finger taps", but seems to have no actual control over the 1-finger tap.  A fix for this problem alone would make the price of BTT well worth it, and I would heartily recommend it on all those threads where people have this problem.
