### ISSUE TITLE
Modified Function Keys not being trapped or sent to apps from touchbar buttons.

### ISSUE THREAD

**Issue by sc-surfer** [folivoraAI/BetterTouchTool#1357]
#### Description of bug/feature request/question:

Modified function key actions not being sent to apps from touchbar buttons.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

2016 MBP

#### Device information:

Type of Mac: 2016 MBP 15"
macOS version: 10.13b
BetterTouchTool version: 2.292

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Pressing the function key combination manually sends the keystrokes to apps, however, BTT buttons do not send the shortcut keystrokes. This appears to only apply to Function keys WHEN MODIFIER KEYS ARE USED, as best as I can see so far. The function key gets sent/recognized when unmodified, but with a modifier in front (i.e. CTL/ALT/SHIFT) it is not sent/recognized.

p.s. Although I'm running OS 10.13b, this problem also existed in 10.12 general release, so probably not related to the beta OS.

Thanks!

Monte

---

**Comment by scoopdreams** [comment]
Not too sure if it is the issue you are describing, but in my use case, the SHIFT modifier key is not being sent when using a touch bar button.

For example in an application I have BTT set up a touch bar button containing SHIFT+CTRL+H. When I press that button in that application, only CTRL+H is sent.

Funny thing is, SHIFT+H works normally.

Hopefully this can be resolved soon.

10.12.6 / BTT 2.297

**Comment by sc-surfer** [comment]
Perhaps the same issue. All the buttons I am having trouble with include the shift key in combination with other modifiers....so, ya, likely the same issue.

Hoping for a fix SOON as this really kills much of the functionality for me.

**Comment by fifafu** [comment]
Uh that's interesting, I'll look into it this evening. Would be great if someone could confirm that only the shift key is affected.

**Comment by sc-surfer** [comment]
I'll see if I can set up some way to trap this...I'm a computer dummy but I'll try. Will report results if I  figure something out.

**Comment by sc-surfer** [comment]
OK, so I set up some buttons that send modified function keys and then used them to enter shortcuts into system preferences/keyboard shortcuts. All were trapped and entered correctly within that context. Doesn't resolve the issuer but adds another datapoint. Hope that helps you track down the issue.

**Comment by Nikolas45** [comment]
I created the following buttons with BTT:
F1
Ctrl-F1
Alt-F1
In all cases, only the "naked" F1 is triggered. Also when I hit the Ctrl or Alt keys on my keyboard an then hit the F1 from BTT.

Cheers,
Nik

**Comment by fifafu** [comment]
@nikolaa45 in which app are you trying to trigger these shortcuts?

**Comment by Nikolas45** [comment]
In wine.

**Comment by fifafu** [comment]
Unfortunately wine and java apps are quite problematic because the default APIs for generating key events don't always work for them.

You could try to add the App to BTTs list of apps, then click the "app specific settings" button and try to enable the shortcut compatibility mode. I'm not sure whether this help but it's worth a try.

**Comment by Nikolas45** [comment]
No, unfortunately that didn't change anything. I noticed something else, though (both with and without compatibility mode):

The Alt-F1 combination seems to send the Alt and the F1 separately to the app. I get a response for both, but not for the combination.

For Ctrl-F1 it is different to what I initially said. Ctrl seems to trigger OS shortcuts (e.g. Ctrl-F3 minimises the window). But that could be a bug with EVE Online, because the official Apple solution (fn-Ctrl-F3) does the same. While fn-Alt-F1/2/3 works as expected. 
I am confused...
