### ISSUE TITLE
[Feature Request] 1/2 page down/up on keyboard

### ISSUE THREAD

**Issue by CalafAnon** [folivoraAI/BetterTouchTool#1422]
Servus!

I would really appreciate it if the Mac Keyboard button for page down/page up (⇞⇟) could be overwritten to only move 1/n pages. I understand that this sounds easy, but really isn't.

I love BTT!

**Comment by dgbeecher** [comment]
This is a nice idea. It would be especially useful for certain websites (like economist.com) that put navigation bars at the top of the page, which somehow aren't taken into account when scrolling the page using page up/down ... meaning that you miss a line of text each time you trigger page up/down (since it's covered by the nav bar).
