### ISSUE TITLE
[Request] Add more precise rules when to show or hide Actions from TouchBar

### ISSUE THREAD

**Issue by chris-scheurle** [folivoraAI/BetterTouchTool#1575]
**Description of bug/feature request/question:**

To make a short story long, I've come up with a somewhat complicated TouchBar setup:

My global TouchBar looks like this (set up in Apple's preferences):

<img width="1085" alt="touch bar bild 2017-10-02 um 23 31 55" src="https://user-images.githubusercontent.com/6209236/31100569-386ed5b4-a7ca-11e7-9cc8-8cb0da938cf1.png">

When I click the "expand" button, I get this:

<img width="1085" alt="touch bar bild 2017-10-02 um 23 33 04" src="https://user-images.githubusercontent.com/6209236/31100584-4a73884a-a7ca-11e7-8464-04f4cbba5243.png">

_Now to the BTT part:_ 

My global settings look like this:
<img width="1127" alt="bildschirmfoto 2017-10-02 um 23 34 53" src="https://user-images.githubusercontent.com/6209236/31100638-905dd46e-a7ca-11e7-844e-533a54d96693.png">
... and the options for some global button would look like:
![bildschirmfoto 2017-10-02 um 23 37 52](https://user-images.githubusercontent.com/6209236/31100749-f9401744-a7ca-11e7-83ec-663daf356594.png)

So now, while I press [option], I get some imitation of the native expanded control strip:

<img width="1085" alt="touch bar bild 2017-10-02 um 23 41 27" src="https://user-images.githubusercontent.com/6209236/31100881-7201bf0c-a7cb-11e7-8a97-b7b6e9c4edf9.png">

... and when I press [shift] _in addition_, some of the keys change their meaning:

<img width="1085" alt="touch bar bild 2017-10-02 um 23 45 03" src="https://user-images.githubusercontent.com/6209236/31101002-0d842276-a7cc-11e7-8d8d-1e0cfaaaabe9.png">

Pressing [control] will show some other, completely unrelated set of actions:

<img width="1085" alt="touch bar bild 2017-10-02 um 23 59 10" src="https://user-images.githubusercontent.com/6209236/31101454-0cbaf49e-a7ce-11e7-9b5a-3ce2e4c9fe4f.png">

 

_My problem:_

When I have some app with App Specific Actions, like:

<img width="1085" alt="touch bar bild 2017-10-03 um 00 03 42" src="https://user-images.githubusercontent.com/6209236/31101582-aff4fc90-a7ce-11e7-8667-afeea7c446aa.png">

... pressing [option] or [control] will result in:

<img width="1085" alt="touch bar bild 2017-10-03 um 00 11 04" src="https://user-images.githubusercontent.com/6209236/31101831-a56168d0-a7cf-11e7-820e-2ecdd87d1c5a.png">
<img width="1085" alt="touch bar bild 2017-10-03 um 00 07 08" src="https://user-images.githubusercontent.com/6209236/31101717-2d9fef56-a7cf-11e7-8c24-af22b8cb355b.png">
<img width="1085" alt="touch bar bild 2017-10-03 um 00 09 24" src="https://user-images.githubusercontent.com/6209236/31101761-61a8804c-a7cf-11e7-8e92-8b95111e1fdb.png">

What I'd _like_ to have is seeing only the global actions while the app specific ones are hidden. Another problem is that I have to define every action multiple times (e.g. the [esc] action: once for "when [option] ist pressed, once for [option][shift] and once for [control]")

 

_Possible solution:_

It would be nice if in the actions' Advanced Configuration dialog you could replace the "Only show while modifiers are pressed" checkbox group by some list "Show this action" defaulting to one entry "Always", where the user can add multiple conditions when to show the action by choosing either "Always", "Never", "No Modifiers" or any combination of [shift], [control], [option] and [command].

Also, it would be nice, if you would move the "Hide global actions if app specific actions are configured in BTT" option to the individual actions' Advanced Configuration dialog.

**Comment by chris-scheurle** [comment]
_Note:_ After thinking about my problem for a bit, I **updated** my request above.

**Comment by chris-scheurle** [comment]
_To clarify:_ for the actions on the screenshots above, I'd like to be able to define:

- **[esc key]** _(global)_: `always` show and _don't_ hide when there are app specific actions.
- **[brightness down]** _(global)_: show on `[option]` **and** `[option]+[shift]`, _don't_ hide when there are app specific actions.
- **[sleep display]** _(global)_: show on `[option]`, _don't_ hide when there are app specific actions.
- **[start screen saver _(global)_: show on `[option]+[shift]`, _don't_ hide when there are app specific actions.
- **[app switcher widget]** _(global)_: show on `[control]`, _hide_ when there are app specific actions.
- **[start]** _(app specific)_: only show on `no modifiers`

 :smile:

**Comment by fifafu** [comment]
Ah that's a pretty impressive setup!
I'll try to make more conditions possible but it's quite tricky and I'm not sure how many users actually have setups that are this complicated...

I'll post here if some or multiple of your requests have been added.

**Comment by chris-scheurle** [comment]
Thank you.  :smile:

**Comment by santip** [comment]
+1 to @chris-scheurle requests.

My use case is that I have setup some windows management related action that all show up when I press the CMD key globally for all apps.

However, for certain apps like my IDE, I have it setup to show the F-keys by default and want to be able to use cmd+F# shortcuts in my IDE, so I would love to have a way to configure certain applications to completely ignore Global actions (even those with key modifiers).

I'm currently overcoming this by setting the equivalent of f-keys for that app with cmd modifier, which overrides the global. This is fine for f-keys but would be impossible in apps where the default app controls would be modifiable by cmd. 

Another useful thing would to be able to create F-keys that are automatically combined with modifier keys. Today, if I create a manual F1 action that is mapped to F1, it will trigger a F1 regardless of what modifier keys I'm pressing. To successfully create it, I need to replicate it for every combination of modifier keys, and I need to do so for any other action I also want showing even when pressing the modifier (otherwise the set of actions changes when I press the modifier and the buttons move around.

Options I can think of for the latter:
 - Add an advanced option to make the "Custom keyboard shortcut" to act in combination with any pressed modifiers.
 - Create widgets for each F-key (although the possibility of giving a custom look to an f-key for certain modifiers is actually appealing to me).

Most of this would be less relevant if it were easier to edit in bulk, or even better, exporting the config to some config file that can be edited externally and imported back in.

Thanks for a great product that makes the touch bar a much more powerful tool.
