### ISSUE TITLE
Multi-finger clicks being mis-recognised

### ISSUE THREAD

**Issue by okoroezenwa** [folivoraAI/BetterTouchTool#1646]
#### Description of bug/feature request/question: 

When multi-finger clicks are set up (3-, 4-, 5-finger clicks), they are sometimes mis-recognised, usually as the one with the smallest number of fingers required. That is, a 4-finger click is recognised as a 3-finger click sometimes, while a 5-finger click is recognised as a 4- or 3-finger click a lot of times. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.): 

MacBook Trackpad

#### Device information:

Type of Mac: MacBook Pro (late 2011)
macOS version: 10.13 (High Sierra)
BetterTouchTool version: 2.290 - 2.310

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Only workaround so far is to find another gesture.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by eshashoua** [comment]
I have this issue too. It was introduced in a recent version. 4-finger clicks not being recognized is the biggest issue. 

**Possibility:** Could this be due to the Advanced Settings > Trackpad > FORCE Touchpad settings that have been introduced? I don't have a force touchpad (2014 MBP). 

**Device Information:**

Type of Mac: Macbook Pro Mid 2014
macOS version: 10.12.5 macOS Sierra
BetterTouchTool version: 2.310 (687)
