### ISSUE TITLE
Mouse wheel programmed to zoom, but does not respond to every turn of the wheel

### ISSUE THREAD

**Issue by Prizm4** [folivoraAI/BetterTouchTool#2095]
#### Description of bug/feature request/question:

Using a normal mouse scroll wheel to zoom in and out. Unless I spin the wheel slowly, not every turn of the wheel executes the shortcut key.

I have Final Cut Pro X and it does not have the ability to zoom in and out of the timeline using the mouse wheel (almost every other editor can do this).
The keyboard shortcuts for zooming in Final Cut Pro are: "CMD -" and "CMD ="
In BTT (Normal Mice section), I assigned those two keyboard shortcuts to "CMD Scroll Down" and "CMD Scroll Up".

It worked, which was great, but unfortunately it does not pick up every turn of the scroll wheel. While scrolling, it will miss two or three turns of the wheel before it zooms in/out again. I have to scroll slowly in order for it to pick up every turn.  Whether this is a limitation of BTT / Final Cut Pro X / or MacOS, I'm not sure.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Normal mouse (Logitech G303)

#### Device information:

Type of Mac: iMac 2017
macOS version: 10.13.3
BetterTouchTool version: 2.340 (719)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
N/A

Thanks

**Comment by waxfingers** [comment]
I haven't test it with a normal mouse, only magic mouse, but I find that if I use an additional action not only the whole thing goes down smoother but I don't have to pre-select the panel where I want the action to take effect, so I just moove the mouse to the viewer and swipe up/down, same regarding the timeline and in both cases it will zoom in/out. It also works with other combination like command + click instead of opt + click and of course you can use the shortcut you prefer. Completely OT but if you haven't check [CommandPost](https://github.com/CommandPost/CommandPost) for further enhancements, tweaks, hacks and goodies

![1st-fc](https://user-images.githubusercontent.com/13238340/36075041-6a8cdeb4-0f40-11e8-9b10-18214018547b.jpg)

![2nd-fc](https://user-images.githubusercontent.com/13238340/36075057-bcaaf898-0f40-11e8-8ed2-ee142b98240e.jpg)

**Comment by Prizm4** [comment]
Thank you very much for your suggestion. I added additional actions that do the same thing. When zooming in tight, it appeared to zoom much smoother.  But what I found was it was zooming twice with each step of the scroll wheel.
This helps the zoom appear smoother when doing large zooms, but if I'm trying to get a specific zoom point, it potentially skips right over it.   I added up to 4 actions that do the same thing, and it was nice and smooth to zoom in and out quickly, but with each turn of the mouse, it was zooming 4 times :D

Thanks a lot for the FCP tool suggestion (CommandPost), I'll have a look at that as well.

**Comment by waxfingers** [comment]
Your welcome +)
Okay @Prizm4, I connected a wireless logitech mouse and assigning zoom in/out to either lateral buttons either to option + scroll works flawlessly. No lag, no jumps, smooth... and must say much smoother than when last tested... a year or so ago... actually, I'm glad I did so, 'cause now I can free buttons 3 and 4 for direct use with other shortcuts. Only thing I set differently from above is using shift instead of option as modifier to use together with the up/down scroll. So can't really reproduce 🐒

iMac // 10.13.3 // BTT 2.340

**Comment by Prizm4** [comment]
Thanks. I just changed the shortcut from Command to Option, but it still won't respond to every mouse wheel turn unless I spin quite slowly.   I was going to try Shift, but Shift+Mouse Wheel already scrolls the timeline horizontally and I think it must be a built in feature, because I could not change this in FCP's shortcuts.
I have found CommandPost works very well for timeline zooming with the mouse wheel. I might have to use that for this purpose.
