### ISSUE TITLE
Applescript keystroke doesn't work

### ISSUE THREAD

**Issue by shimj** [folivoraAI/BetterTouchTool#2232]
#### Description of bug:
Applescript keystroke doesn't work. For example, when using shortcut "⌘⌥+c" to call Applescript to keystroke "⌘+k", it dose "⌘⌥+k".

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

keyboard

#### Device information:

Type of Mac: MacBook Pro 2017
macOS version: 10.13.3
BetterTouchTool version: 2.403

**Comment by fifafu** [comment]
Which Apple Script action are you using to trigger the script? If you are using "in background", try the other one instead.
This may however not be fixable because BTT can only influence the modifier keys in it's own context.

**Comment by shimj** [comment]
I have tried the other one, the problem still exists. This problem didn't appear in the versions before 2.400, all the shortcuts are added long long ago and they worked well...

**Comment by shimj** [comment]
I just found that my problem is not caused by the above problem... Actually, the problem is as follows:
I use double tap to trigger applescript which contains keystroke "⌘⌥+F", and I also set "⌘⌥+F" to trigger something. However, double tap will do nothing.

**Comment by fifafu** [comment]
Ah sorry this doesn't work with the new shortcut implementation because it intercepts keyboard events at a lower level. (You can enable the old implementation in the old preferences, but then the new features won't work).

However you can use a different method to trigger the other action from Apple Script.
In BTT right-click your shortcut and click "Copy Link To Trigger".

Then in Apple Script, instead of sending the shortcut, open that link. E.g.
```open location "btt://8440C3C5-0CE7-423E-AB9E-7D68FEABA569"```. This will trigger the action in BTT.

![image](https://user-images.githubusercontent.com/8820811/37449987-9001814a-282c-11e8-9760-40b09d39c4b0.png)

**Comment by shimj** [comment]
Thanks for your detailed solutions. As I tested, "Open location" is much slower than keystroke. If "Open location" can be optimized, it would be great.

**Comment by fifafu** [comment]
In my tests this is pretty much instant. Make sure the BTT window is closed when testing.

**Comment by shimj** [comment]
I closed the window, but it is still slow, I think it costs about 0.8s whereas using shortcut costs about 0.2s.

**Comment by fifafu** [comment]
Mhm can't seem to reproduce on my system, seems to trigger immediately here.
Then the only solution is to use the old keyboard implementation:

![image](https://user-images.githubusercontent.com/8820811/37451672-8ad80be8-2832-11e8-814f-867361da7169.png)

**Comment by shimj** [comment]
OK, thanks again.

**Comment by mikeweilgart** [comment]
@fifafu Related issue with triggering Applescript.  It turned out to be the key "F12" that I was attempting to use to activate it.  That won't work with the new keyboard implementation (although F15 on my external keyboard will), but F12 does work (on external keyboard or built in keyboard) *only* when the "always use old keyboard shortcut implementation" is checked.  Seems like a bug; could you look into it please?
