### ISSUE TITLE
Support Logitech Craft keyboards

### ISSUE THREAD

**Issue by YoSafeguard** [folivoraAI/BetterTouchTool#2389]
Hello!
Respond please, there are plans to support the keyboard of the Logitech Craft keyboard.
The Logitech software runs very poorly and supports a limited number of programs.
I would very much like to see the support of this keyboard in your wonderful program !!!
Thank you!

**Comment by MarqueIV** [comment]
I'd love to see this support too.  Granted, really it's just the wheel that needs support as it's otherwise just a keyboard, but it would be nice.

That said, there's a temporary thing you can do, and that's to assign keyboard shortcuts to the wheel, then use BetterTouchTool to respond to those keyboard shortcuts.  Since I never use the higher Fxx keys, I can use those.  Again, it's a bit of a hack and doesn't let us use the 'freespin' mode of it, but it's something.

Another thing I may actually try is to look into ControllerMate (haven't fired that up in a while) to see if it's recognized in that app.  If it is, from there you can basically make it do whatever you want since you're graphically messing with HID devices and the like.  BTT+ControllerMate is a pretty powerful (but complex) solution.  For now, that's why I'd just stick with the keyboard technique mentioned above.

**Comment by tweh** [comment]
:+1:

I support this request.
