### ISSUE TITLE
Right Click Unstable MacOS 10.13.4 / BTT 2.422

### ISSUE THREAD

**Issue by orbitly** [folivoraAI/BetterTouchTool#2461]
Secondary click (using the trackpad) has been appearing for a split second and then disappears while BTT is open for the past week or two, works fine when I quit BTT. Sometimes it's every other right click that doesn't work.

**Comment by fifafu** [comment]
Do you have a two finger gesture configured in BTT?

**Comment by orbitly** [comment]
Nope 
<img width="659" alt="screen shot 2018-04-16 at 1 31 32 pm" src="https://user-images.githubusercontent.com/6829441/38833513-97cabd1c-417a-11e8-88a7-60ef67905a47.png">

**Comment by fifafu** [comment]
Unfortunately  I haven't heard of such an issue before.

Could you attach an export of your preset? (Manage presets -> export)

**Comment by orbitly** [comment]
https://www.icloud.com/iclouddrive/09sONvkG4KCSbfV5uyd763Qbg#Default

**Comment by fifafu** [comment]
Weird, your preset seems to work fine here.

The only thing that could potentially conflict with two finger clicks is the three finger click => middle click mapping. 

Do you maybe have three finger dragging enabled in System Preferences =>  Accessibility => Mouse & Trackpad => Trackpad Options? (asking because that setting can be problematic)
