### ISSUE TITLE
Feature request 2: Scitex-style lines projecting from clickpoint

### ISSUE THREAD

**Issue by peetwright** [folivoraAI/BetterTouchTool#2515]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead. 

---

#### Description of bug/feature request/question:
This is another suggestion that I'd love to see. Triggered, always on, as well as customizable in alpha/transparency and color. In the old Scitex days (pre-photoshop) the cursor would be followed on-screen with a horizontal line and a vertical line that intersected at the mouse pointer. When working on crowded screens, or on highly detailed images in Photoshop - it's easy to lose the pointer temporarily and while Apple has helped by adding the wiggle to grow function, it's kind of a meh solution. I'd love to be able to run with the full-width lines if possible. Again, like my other request this one steps slightly outside of the BTT box, but hopefully you can consider it. 

Some software today, like most CAD packages, still support this and call it full screen crosshairs. Here is an image of one in autocad...

http://www.2dprofessor.com/increase-crosshair-size-autocad.html

Many thanks for years of really great stuff!

#### Device information:

Type of Mac: Imac 5k 
macOS version: 10.13.4
BetterTouchTool version: 2.444

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
While I could add something like this, it would probably be very bad for performance and would cause various issues.

The only way to implement this as an external app would be to place a big  transparent window over the screen and draw the lines into it as far as I know. This would use a lot of memory and also performance issues because every click would need to travel through that transparent window.

This is why I currently don't think I will add this. .-(
