### ISSUE TITLE
[Question] How to disable BTT when switching between apps (⌘+tab)?

### ISSUE THREAD

**Issue by juanbrena** [folivoraAI/BetterTouchTool#2585]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at andreas@folivora.ai instead. 

---

#### Description of bug/feature request/question:

I switch between apps with (⌘+tab) a lot and sometimes use my arrow keys to go to a specific app. The problem is I have BTT shortcuts (⌘+ ←) and  (⌘+ →) to maximize window left and to maximize window right respectively. So when I want to switch between apps by (⌘+tab+ ← or →), I trigger the BTT shortcuts instead of switching left or right to pick the specify app I want. 

This was not an issue until I updated and it just started acting this way.  

Any help is appreciated. Thanks 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard

#### Device information:

Type of Mac: MacBook Pro (Retina, 13-inch, Mid 2014)
macOS version: 10.13.3
BetterTouchTool version: 2.426

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by juanbrena** [comment]
b

**Comment by fifafu** [comment]
Unfortunately that's not possible because there is no API to know when the app switcher is active.
You can try to enable the old shortcut implementation in the advanced preferences:

I think the old keyboard shortcut implementation may not work while the switcher is open, so this may workaround your issue
![image](https://user-images.githubusercontent.com/8820811/39692911-97f31ee2-51e2-11e8-8121-a77434b4274b.png)
