### ISSUE TITLE
Feature request: Elgato Stream Deck support

### ISSUE THREAD

**Issue by bountyvcs** [folivoraAI/BetterTouchTool#2595]
Hi,

I have recently purchased an Elgato Stream Deck for the express purpose of productivity. The idea was to use the Stream Deck in conjunction with BTT for even faster access to my BTT presets. The Stream Deck can send hotkeys to specific apps depending on which app has focus and I thought that I could use this to send hotkeys that I've set up in BTT, primarily to insert large amounts of code to Sublime Text (the Stream Deck itself is limited to 200 chars with its inbuilt functionality).

Unfortunately, it appears that Stream Deck is sending the hotkeys directly to Sublime Text and BTT is not picking them up.  I imagine that this is due to BTT listening for actual key presses on the hardware keyboard.

Is it possible to add support for the Stream Deck?

Many thanks and please keep up the great work with BTT - it's hands down the most useful app on my Mac.

Ben

---

#### Description of bug/feature request/question:
Please only post one bug or feature request per issue.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Elgato Stream Deck

#### Device information:

Type of Mac: Late 2016 MBP
macOS version: 10.12.6 (16G1314)
BetterTouchTool version: 2.246

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by juliosecco** [comment]
Hi,
same wish here,
but I don't think that's a problem of BTT and hotkeys not got by BTT,
since I have bypassed for the moment the thing using Alfred (a really nice launcher and workflow manager)

1) Stream Deck fires the hotkey (and Alfred is able to intercept it)

2) a simple workflow in Alfred is fired by the hotkey, and dispatches himself an hotkey, that is indeed captured by BTT that handles the thing.

I don't have idea because a direct call by Stream deck does not work, and this double passage works, but I would like a simpler solution, too.

**Comment by juliosecco** [comment]
UPDATE:
now an hotkey is dispatched to Alfred, that launches using applescript a BBT action
