### ISSUE TITLE
Feature Request : align/resize a selection windows at launch automatically

### ISSUE THREAD

**Issue by TheBartoMan** [folivoraAI/BetterTouchTool#2602]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at andreas@folivora.ai instead. 

---

#### Description of bug/feature request/question:
Please only post one bug or feature request per issue.
Feature Request

When I start up my Macbook for the working day, I place various application in various places on my screens. (By dragging them to snap areas)

i.e. My Outlook is down the left side of my external monitor, with Safari taking up the rest of the screen. My Lync Messenger is on another screen in a specific location.

Can I place all these applications into their required snap areas automatically when each application launches without having to drag them?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Macbook

#### Device information:

Type of Mac: Macbook Pro
macOS version: 10.13.4
BetterTouchTool version: 2.467 (825)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by andyconlin** [comment]
@TheBartoMan, I had an idea while reading this which could serve as a workaround until this becomes a feature.  You may have considered this already, but you could create a series of actions to launch the various programs and resize/move them.  It doesn't do exactly what you ask (position an app's window on launch), but if it fits your workflow, it could solve it a step deeper.

You could create an action with additional actions within BTT or it could be done via Automator (which could be packaged as a self-made "Launcher" app that is opened on login, as a Calendar Alarm, or as a standard workflow).

I don't know your experience or comfort level with these, but if I can help in any way, let me know!  I'd be happy to do what I can.

P.S. I am replying here because this feature request is not yet in (the new community setup)[https://community.folivora.ai/c/feature-requests].  I'm not sure if we should continue the discussion here or there, but just (asked)[https://twitter.com/andyconlin/status/998315787705356289] @fifafu about it so we'll know what's most helpful.
