### ISSUE TITLE
Center window through custom move/resize (BTT 2.467)

### ISSUE THREAD

**Issue by RowanKaag** [folivoraAI/BetterTouchTool#2604]
#### Description of bug/feature request/question:
(Reference to #1194) With the addition of 'Custom Move/Resize' I have performed my first attempt to create new gestures in order to get rid of SizeUp (which currently handles my window resizing). I've managed to get "Full Screen" (not macOS native) working but am struggling with centering my window.

**Environment:**
- 1440x900 monitor
- alt+cmd+m shortcut

**Expected result:**
- Currently active window is adjusted to 1300x800
- X coordinate is adjusted +70 from X=0, Y coordinate is adjusted +50 from Y=0

**Actual result:**
- Currently active window is adjusted to 1230x720
- X coordinate is adjusted +70 from X=0, Y coordinate is adjusted +20 from Y=0

---

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard

---

#### Device information:

Type of Mac: MacBook Air 2012
macOS version: 10.13.4 (17E202)
BetterTouchTool version: 2.467

---

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
**Expected result:**
![screen shot 2018-05-01 at 14 30 20](https://user-images.githubusercontent.com/6907625/39472874-392d6a6a-4d4c-11e8-9cfe-fb86fb06b160.png)

**Actual result:**
![screen shot 2018-05-01 at 14 28 55](https://user-images.githubusercontent.com/6907625/39472876-3fb74f04-4d4c-11e8-986b-92b335090a73.png)

**Comment by fifafu** [comment]
Could you post a screenshot of your config?
This should center a window on a monitor:

![image](https://user-images.githubusercontent.com/8820811/39473021-0063d9fc-4d4d-11e8-80c2-0566978b8576.png)

**Comment by RowanKaag** [comment]
I think I'm going Looney Tunes. I could swear having those exact settings before and it had some rather special outcomes. Now by applying the settings you provided it works as expected. Just for reference, here were my latest settings before applying yours.

![screen shot 2018-05-01 at 14 41 53](https://user-images.githubusercontent.com/6907625/39473254-26c151aa-4d4e-11e8-8156-5fd9a6ab2556.png)

**Comment by fifafu** [comment]
Hehe, well it's a bit complicated to get how this configuration works. I'll soon add it to the documentation and rename some of the labels to make it more clear.

Basically you define the origin (x=0,y=0) of a window BTT will move. In your screenshot that would be the top left corner of the window. Then you select the origin of the position on the screen from which the selected window origin shall be moved. In your case that would be the top left corner of the screen.

Now your setup means: "Position the top left corner of the window 70px to the right (from the top left corner of the screen) and move it 50px up (from the top left corner of the screen)."
And because it is not possible to move windows higher than the menubar, the outcome is that it is positioned directly below the menubar.

**Comment by RowanKaag** [comment]
Ah, that does explain the behaviour in the set-up I provided. Thank you for the detailed explanation.

I've slightly adjusted your settings now for my own use case to also resize the window as I want all windows to always be the same size when centering. This is just personal preference ofcourse, but I like having a main window in focus and keep gutters on the sides. This creates a sense of depth for me (purely psychological I suppose) to keep a slightly relaxed workflow in stead of a fullscreen window. In addition I use HazeOver to darken everything around the focused window.

Thank you heaps for adding this to BTT. Glad I can move this functionality from SizeUp over to BTT. Also still happily using the snap area's function when working with a mouse!

![screen shot 2018-05-01 at 18 03 44](https://user-images.githubusercontent.com/6907625/39481079-84473d8c-4d6a-11e8-877a-12b9e8f9f68f.png)
