### ISSUE TITLE
feedback in Setting needed.

### ISSUE THREAD

**Issue by idmah** [folivoraAI/BetterTouchTool#2677]
Love this software.
But It took me a full 15 mins to configure the triple finger triple tap, which is what I bought it for.

So my idea is add small track pad display that displays what the software is seeing the gestures as
and a selector at to what the user intended. Provide feedback and education.
Training the user train the software both.

Then provide Learn mode/ window.
So I would select three finger double tap. then Do the gesture it would record what I did.
And ask me to do it a few times, then popup "would you like me to adjust the three finger double tap speed to your preference"

Just my thoughts.
thanks for a great utility!
Ian

**Comment by fifafu** [comment]
Hi Ian,

unfortunately this is not possible with the current implementation and it is unlikely that it can be added. BetterTouchTool can only recognize gestures after they have been added, because it needs to know which other gestures are configured in order to do the correct recognition optimizations.

You can open the live view to see how your fingers are touching the trackpad, but it also will only recognize configured gestures correctly.

![image](https://user-images.githubusercontent.com/8820811/39913440-26dce95e-5502-11e8-9b8f-b4cb08d7bbc8.png)

Maybe if I ever change the recognition to some other model, based on machine learning this would become possible. But this is currently very unlikely.
