### ISSUE TITLE
BTT splash screen (and now GDPR compliance confirmation) always opens up on wake/startup

### ISSUE THREAD

**Issue by r00fus** [folivoraAI/BetterTouchTool#2711]
#### Description of bug/feature request/question:
The full-modal splash screen that shows up when starting BTT for the first time does so *every* time I wake/unlock my mac.   This is terribly annoying.   Now it's become a bigger chore in the v2.503 as the GDPR check now causes *3* clicks to close all the windows before every time I do anything on my mac. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Entire Macbook. 

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2017) - with Touchbar
macOS version: macOS 10.12.6
BetterTouchTool version: 2.503 (though the basic splash screen since 2.4x has been showing)

**Comment by fifafu** [comment]
This probably means that BTT can not write to it's settings file due to a file permission error.
The easiest solution would be to delete the ~/Library/Preferences/com.hegenberg.BetterTouchTool.plist (BTT will then create a new one with the correct permissions).

Alternatively have a look at https://support.apple.com/en-au/HT203538

**Comment by r00fus** [comment]
Thanks Andreas.

This cleared it up!
Man, I was going batty trying to avoid this on conf calls.  Now I will
continue to recommend BTT to my friends :)

Raj
(408) 702-2230

On Wed, May 16, 2018 at 6:38 AM, Andreas Hegenberg <notifications@github.com
