### ISSUE TITLE
3 Fingers Not Haptic-Clicking on Magic Trackpad

### ISSUE THREAD

**Issue by stuartjmoore** [folivoraAI/BetterTouchTool#2730]
**Describe the bug**
When 3 finger clicking on a Magic Trackpad, the device no longer “clicks” (but the action still works).

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**
Magic Trackpad

**Device information:**
- Type of Mac: MacBook Pro Retina
- macOS version: 10.13.4 (17E202)
- BetterTouchTool version: 2.427 (787)

**Comment by stuartjmoore** [comment]
Any ideas? I just bought a lifetime license and updated to the latest version: 2.512 (849); and it’s still broken.

**Comment by fifafu** [comment]
you could try to change the haptic feedback in the advanced trackpad settings to one of the "new" ones. I have had a few users during the last few years where the default ones didn't work (it seems to be caused by a broken MacOS update and only completely reinstalling fixes it).

The "new" styles use a different api that doesn't seem to be affected by this.
