### ISSUE TITLE
button group closes upon button touch / when switching to a different app

### ISSUE THREAD

**Issue by moseylevy** [folivoraAI/BetterTouchTool#369]
re: touchbar
OS 10.12.2
BTT 2.01 (597)

when using a button group, 
if I put a switch app button in there, and I press it, it closes the button group after press.
it should keep the button group open until I choose to close the button group, or make It an option.

**Comment by fifafu** [comment]
Good point (this is because the Touch Bar refreshes when a new application comes to front). I'll think about a way to prevent this for global groups.

**Comment by moseylevy** [comment]
Great thanks!

**Comment by kdumovic** [comment]
Hi @fifafu - Any update on this? I would love there to be an option for touch bar groups not to close when I switch applications. This allows me to configure different states to my global touch bar (each corresponding to a different button group). For example, I have a state for Spotify display info and controls, another state for SoundCloud, and another state with stock tickers. However since the touch bar always resets on application change, I have to select a button group and trigger that state every time, which defeats the purpose of having that information there at a glance.

**Comment by kdumovic** [comment]
Hoping for a fix soon. 🤞

**Comment by spnkr** [comment]
+1
