### ISSUE TITLE
"2 Finger Swipe From Right Edge" isn't working for me

### ISSUE THREAD

**Issue by Thomas-Redding** [folivoraAI/BetterTouchTool#375]
As the title says, it appears that "2 Finger Swipe From Right Edge" isn't working for me. I should note that swiping from the left edge *is* working.

I'm using running BTT 2.02 on Sierra 10.12.2.

In terms of hardware, I'm using a trackpad on a mid-2012 13" Macbook Pro laptop.

Thank you for all you hard work - this app is really stellar!

**Comment by codedependant** [comment]
I seem to be having a similar problem since updating to version 2.071. 

Neither "2 Finger Swipe From Right Edge" or "2 Finger Swipe From Left Edge" seem to be working. In the Live View the gestures are not registering at all. When I change them to Top/Bottom it works fine.

Im on OSX 10.11.6 using a 2013 Macbook Pro.
