### ISSUE TITLE
[FEATURE] Ability to force strict tap detection via advanced setting

### ISSUE THREAD

**Issue by ghost** [folivoraAI/BetterTouchTool#476]
#### Description of your bug/question/feature request...:

The OS has a "4 finger pinch" gesture to show the desktop, which I use constantly.

BetterTouchTool interprets that 4-finger pinch as its own "4 finger tap" even though I'm putting 4 fingers down (a "tap") but without letting go I am spreading them or pinching them!

I wanted to have "start drawing gesture" on 4 finger tap... but now, any time I pinch/spread to show my desktop, I get the "bettertouchtool drawing" overlay on my screen.

Please revise all of the X-finger tap gestures in BetterTouchTool to ignore them if the user starts spreading/pinching their fingers, so that you don't misidentify pinching as tapping.

**What kind of Mac are you using?**

MacBook Pro 2010 15"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

MacBook's own Trackpad

**Which versions of macOS and BetterTouchTool are you running?**

macOS Sierra and BetterTouchTool 2.04

**Comment by SteveJobzniak** [comment]
For now I am using a workaround: Do the 4-finger pinch/spread to show/hide the desktop, and then immediately tap once with a finger to abort BetterTouchTool's drawing.

**Comment by fifafu** [comment]
Hi,

sorry if you are using BTT you have to disable the system gestures, there is no way to make both work in parallel without causing such conflicts. 

However you can reconfigure 4 finger pinches using the "Pinch with thumb and 3 fingers" gesture in BTT. Maybe this can work for your usecase.

Best,
Andreas

**Comment by SteveJobzniak** [comment]
@fifafu Conflicts will only happen if I bind the same gesture in macOS and in BetterTouchTool.

This is not the same gesture.

But okay, I have now disabled System Preferences - Trackpad - Show Desktop (4 finger spread).

The bug in BetterTouchTool remains: If I put 4 fingers on the touchpad and spread them, it still registers it as a 4 finger tap.

The bug in BetterTouchTool: Tap == Spread/Pinch.

The fix for BetterTouchTool: Tap != Spread/Pinch.

Please reopen this ticket so we can discuss the bug.

;-)

**Comment by fifafu** [comment]
No, unfortunately the conflict will also happen with different gestures because BTT doesn't know anything about the state of the system gestures. Only if the gestures are configured in BTT it can take the measures that are necessary to prevent false triggering.

So if you assign actions to the pinch with thumb and 3 fingers in BTT it won't trigger a 4 finger tap anymore if a spread is recognized.

**Comment by SteveJobzniak** [comment]
@fifafu Okay thanks for that, that is an improvement at least.

But then this question is important: Why is BTT detecting spread/pinch as a tap at all? It's not a tap.

So why only restrict BTT's detection to "correct taps only" when you add multiple gestures? Why not always run the code that detects taps as taps, instead of detecting taps as tap, pinch, spread, slide, etc?

**Comment by fifafu** [comment]
I have tried that previously, but it turned out that different people tend to tap in very different ways and every step to limit them has resulted in lots of negative feedback :-)
That's probably why Apple doesn't really have three & four finger taps.

**Comment by SteveJobzniak** [comment]
@fifafu Ah I understand. As a developer, I totally understand the flood of user emails that come after changes like that. ;) But please, can you add a hidden ~/Library/Preferences plist preference at least? To "forceStrictTapDetection==true" in the plist file? Or even better, in the GUI's advanced settings somewhere. Because trust me I would run with that always on. One of my biggest annoyances in BTT is how often it thinks I've tapped when I did something else. :)

**Comment by fifafu** [comment]
yep, adding a setting to the advanced settings is a good idea!

**Comment by SteveJobzniak** [comment]
@fifafu Thank you so much. <3 It will be great to finally have rock-solid gestures in BTT after that.

**Comment by fifafu** [comment]
I'll add a slider that'll let you specify the maximum allowed movement of the fingers for them to be still recognized as a tap.
That may also help to find the sweet spot that works best for most users.

**Comment by SteveJobzniak** [comment]
@fifafu Very nice, that sounds excellent!
