### ISSUE TITLE
[Feature Request] ... to Previous Monitor

### ISSUE THREAD

**Issue by joshuasmay** [folivoraAI/BetterTouchTool#514]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
I have a three monitor setup, don't use Spaces, but I find it incredibly useful being able to move my app windows between my monitors if I'm doing a demo or running through a document with a colleague. Right now I can use the **... to Next Monitor** command to move a window in one direction around my monitors, but it would be great if the equivalent **... to Previous Monitor** command existed so I didn't have to cycle a window through every monitor to get back to the first.

**What kind of Mac are you using?**
mid-2015 MacBook Pro 15"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Magic Keyboard v2

**Which versions of macOS and BetterTouchTool are you running?**
macOS: 10.12.3
BTT: 2.071

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
![previous monitor](https://cloud.githubusercontent.com/assets/21123532/23123037/a8de26be-f75e-11e6-9ca2-c7c98901ff3f.png)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by markjbishop** [comment]
+1

**Comment by sebastianhaberey** [comment]
+1

**Comment by djohnsen** [comment]
Also +1. I presently have [Spectacle](https://www.spectacleapp.com/) installed on my system with only the hotkeys for previous/next window enabled (and then mapped into touchpad swipes via BTT).

**Comment by moshed** [comment]
I would love this feature as well. looking forward!

**Comment by rmatec** [comment]
This is the only thing preventing me from buying a license. I'll stick to SizeUp for now.

**Comment by bryansteiner** [comment]
+1

**Comment by fastmover** [comment]
+1

**Comment by leanazulyoro** [comment]
+1 also have a three monitor setup and this would be very useful

**Comment by fifafu** [comment]
In v2.460 (alpha) there is a new predefined action which can do all sorts of custom window moving and resizing:
![image](https://user-images.githubusercontent.com/8820811/39365653-08ef6b04-4a32-11e8-98be-4befc40b4506.png)

**Comment by sebastianhaberey** [comment]
Hey Andreas I tested this today and it works fine for me. Thanks for your work on this!

**Comment by mjewell** [comment]
Maybe I am misunderstanding something but I still can't seem to get this to work:

My set up looks like this:

![image](https://user-images.githubusercontent.com/8717271/44282440-f0070080-a20f-11e8-8de5-038ceb2a1b26.png)

And this seems to be approximately what I want:

![image](https://user-images.githubusercontent.com/8717271/44282431-dfef2100-a20f-11e8-9822-73b2f96ee33a.png)

but it doesn't quite work, since you can only move directionally, but I really want to cycle through them. Doing `left` or `right` will get stuck cycling between the top 2 monitors, and doing `up` or `down` will get stuck cycling between the top right and bottom monitor. Using the built in `next monitor` action cycles through all 3 in the desired way.

It seems like there should be another option for `next`/`previous` along with `left`/`right`/`up`/`down`

**Comment by wagnerone** [comment]
It never ceases to amaze me how many options BTT has!

I have the same monitor setup as @mjewell and the same enhancement request.
