### ISSUE TITLE
[FEATURE] Expanded trackpad/magic mouse gesture library

### ISSUE THREAD

**Issue by ghost** [folivoraAI/BetterTouchTool#552]
I've recently returned to BTT from Jitouch. You know me as Johnny on email, and we discussed the MacBook Pro 2010's graphics card issues.

I'm glad to be back with BTT now that the discrete GPU is no longer triggered on Sierra. Because BTT is a much more powerful application.

But I am in a lot of pain. The trackpad/magic mouse gestures available in BTT are awful. After having used Jitouch for 5 months, I even contemplated never going back to BTT, because BTT's gestures are so bad. But today I decided I'll return to BTT after all, because the extra power in your application is worth it.

The gestures in BTT aren't very ergonomic. A lot of them have weird sequences of finger presses or swipes. There isn't much variation.

In Jitouch, most gestures are 2, max 3 fingers. And they are **extremely** ergonomic.

You can see some of their list here: https://www.jitouch.com/trackpad/ and https://www.jitouch.com/magicmouse/.

Here are the ones I can't live without:

- 1 finger held on pad, 1 finger tapped to the left of it: Previous tab.
- 1 finger held on pad, 1 finger tapped to the right of it: Next tab.
- 1 finger held on pad, 1 finger placed on pad and slide down: Toggle window move/resize tool.
- 1 finger held on pad, 2 fingers placed on pad and slide down: Close/close tab.
- 1 finger CLICKED on pad, 2 fingers placed on pad and slide down: Quit.
- 2 fingers held on pad, 1 finger double-tapped to the left of it: Refresh.
- 4 fingers held on pad, added one by one, from pinky to index (like rolling your fingers on the pad): Hide.
- 4 fingers held on pad, added one by one, from index to pinky (like rolling your fingers on the pad): Fullscreen.

All of these will make sense if you install Jitouch and try it. Its gestures are _far beyond_ what's in BTT. And that's kind of sad since BTT is a 10x more powerful tool in all other areas!

I know that BTT grew organically as a hobby product. Perhaps now that it's commercial, it's worth adding these extra, super ergonomic gestures? There's nothing better on the market as far as gestures go. So hopefully BTT will catch up. It's very painful to be back with BTT's unergonomic gestures. :-/

It's making me bind LESS gestures in BTT, since the gestures are so unergonomic and only a few are usable. So I'm missing out by being back to BTT.

I love BTT in every other way. ;-)

**Comment by fifafu** [comment]
Hey,

First three sound like tip tap left, tip tap right and tipswipes.
BTT also has clickswipes (e.g. three finger click swipes ).
Last two ones sound like the custom 4 finger gestures in BTT.

I'm not trying to compete with Jitouch and there will always be differences in the gesture set of both. 
However of course BTT will continue to evolve and additional gestures may be added. (although there is no difference now that it's paid. The time I can work on it is still the same)

Honestly you might be better off with Jitouch because I'm currently quite happy with the gestures offered in BTT and it might be quite a while before any new ones are added (currently focusing on other things).  I have always added the gestures/features I liked and will continue doing so, I think that was/is a big part in BTT's success 😉

**Comment by SteveJobzniak** [comment]
Hey man! :-)

Alright, so first off:

> "First three sound like tip tap left, tip tap right and tipswipes."

Yes! Turns out you've added "TipTap Left (1 Finger Fix)", which does exactly what the "1 fix, 1 tap on the side" gestures in Jitouch do. I've never seen that BTT gesture before. I've only seen the "2 finger fix" versions and above, which are hard to use. Maybe the 1-finger version has always existed for as long as 2 finger, but I've certainly not noticed it before! Thanks!

> tipswipes

Yes, I am aware of those in BTT and I think they're very hard to use. In BTT they require two fixed fingers. Having two fingers fixed on the trackpad "locks" my joints very rigidly.

Jitouch does the opposite: You have ONE finger fixed, and then do a swipe with 1 or 2 extra fingers. This lets your hand pivot ergonomically around the single finger that's held down. Or it lets you "put the index finger on your pad and scrape with two fingers next to it".

It's a very ergonomic gesture that I'm missing badly in BTT. :-)

> BTT also has clickswipes (e.g. three finger click swipes ).

Yeah, but all of those 3 finger swipes are hard to use so I've avoided them. Especially the ones that require a click before swiping. It adds lots of frictions to the pad.

> Last two ones sound like the custom 4 finger gestures in BTT.

Yep, I'm aware of those and knew I could replicate it, but figured it would be good if they existed built-in. They're very nice: Just roll 4 fingers onto the pad (pinky-to-index and index-to-pinky). Very logical gesture.

I'll try to get by with the discovered "TipTap Left (1 Finger Fix)" and the custom gestures.

But yeah I still recommend that you install Jitouch and make note of some of them. They're filling in useful blanks that aren't available in BTT. That's a good thing. ;-)
