### ISSUE TITLE
FEATURE REQUEST! - Secondary touchbar

### ISSUE THREAD

**Issue by pallavmac** [folivoraAI/BetterTouchTool#690]
It would be amazing for a feature like when you hold the FN key on Mac. 
Could you have a page or something on BTT for a secondary custom touchbar that shows up while FN is held? This could have quick actions which we can use and is an amazing feature so that instead of F1,F2 key etc. I get BTT actions. I tried doing something by setting a key sequence of only FN key down but I can't get it to show only while the FN is being held. It would be an AMAZING feature.

**Comment by Toastrackenigma** [comment]
<img width="811" alt="screen shot 2017-03-21 at 5 54 48 pm" src="https://cloud.githubusercontent.com/assets/19319807/24133180/ba22c9b2-0e5f-11e7-8c8a-68b929484da5.png">
This is already kind of a thing, except with ctrl / option / shift / command rather than fn. Just hit "Advanced Configuration" and then select when to show it (both highlighted in my screenshot).<br><br>
I'm almost certain that fn is reserved, so that the user still can access the function (F1 - F12) keys unobstructed.

**Comment by fifafu** [comment]
I'll check if this is possible - currently I don't think the FN behavior can be overridden, but I'll check again!

**Comment by pallavmac** [comment]
Just to clarify I don't think it HAS to be the FN let that would do these actions. It's only the most convenient but a different modfiifer key would be fine. 

Also I would like to clarify that the feature would work best if the touch bar could temporarily show up even when the apple default touch bar is on the screen.
