### ISSUE TITLE
Modifier keys cause BTT Touchbar Toggle

### ISSUE THREAD

**Issue by sentre3000** [folivoraAI/BetterTouchTool#739]
#### Description of bug/feature request/question:

Modifier keys like Shift, Command, etc, cause  BTT Touchbar to toggle back On. This is only when you have any buttons/widgets configured with "Only when modifiers are pressed" option.

Example:

I have few buttons configured to show up only when Shift is pressed. I toggle BTT Touchbar off.  I press and release Shift key, it toggles back BTT Touchbar.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touchbar

#### Device information:

Type of Mac: MacBook Pro 13"
macOS version: 10.12.3 (16D30)
BetterTouchTool version: 2.071 (608)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by someToast** [comment]
This also kills Touch Bar functionality in other apps that use modifiers.

For example, if I have the default system Touch Bar showing and try to do Shift + volume buttons, the system bar collapses and BTT replaces it as soon as I touch Shift.

Also, having different custom icons for the normal and shifted BTT button states is annoying, because every time you tap the Shift key **anywhere,** the Touch Bar layout refreshes.
