### ISSUE TITLE
[Feature request] BTT Remote Bluetooth support

### ISSUE THREAD

**Issue by filipsuk** [folivoraAI/BetterTouchTool#747]
#### Description of bug/feature request/question:
It would be great to control my mac with iPhone BTT Remote via bluetooth. One particular use case is presentations in foreign environment (phone and computer are not on the same wifi / wifi does not work etc.)

#### Affected input device:
BTT Remote on iPhone

Thanks for your awesome software!

**Comment by fifafu** [comment]
Yes, I'll add bluetooth support, however I currently can't give a timeframe when it will be there. "Sometime this summer" (with a bigger re-design of BTT Remote)

**Comment by KrisGL** [comment]
I would also highly value this feature

**Comment by Askern** [comment]
Hello what about this function? I would love to see this function in BTT! I am a teacher going to different places with bad or no wifi connections. This function is crucial for me!

E.g this app http://www.mobilemouse.com/support.html already can create a No-Wifi connection with the Mac and and the iPhone. Sadly my Mac is from 2011 so it doesn't have Bluetooth 4.0 (Bluetooth LE), so I cannot use the function within this app. 

Also its Possible to create an Ad-Hoc Network, but this is insecure, because Apple disabled the chance to add a password protection to a self created Network since Mavericks.

https://www.engadget.com/2009/09/25/mac-101-create-a-wireless-network-between-mac-and-iphone/

http://www.delora.com/advice/networking_guide/adhoc_wifi2/

An Update on this issue would be awesome!

**Comment by fifafu** [comment]
Hey,

Bluetooth support will come with an upcoming version, however it will definitely require Bluetooth LE. Unfortunately there won't be support for any other adhoc networking, so the 2011 Mac will only be able to use it with a bluetooth le dongle.

**Comment by Askern** [comment]
Thank you!

**Comment by Askern** [comment]
Just wanted to ask about this again. It would be a "killer-feature" since I know many teachers who buy extra bluetooth sticks to control their Mac Presentation. And they hate it to carry around one extra tool with them. Hoping that it is still being work on.

**Comment by 760leldridge** [comment]
i would like to see this as well , maybe even also an option for cable linking.. i like to use it specifically for hotkeys in my software.

Another cool suggestion would be the ability to customize the interface more, mainly the layout of of the "buttons" , rather than just a long list, maybe  have the option to fill the entire screen with macros/hotkeys/whtever. I LOVE YOUR WORK!?! Been using this for almost a couple years now and is heavily integrated into my work flow, this is truly such an amazing idea , thank you!!!

**Comment by deepsweet** [comment]
Sorry for pinging this again, but is there any news? Hope that it wasn't closed 2 days ago just to clean up staled issues, I'm very interested in BTT Remote without Wi-Fi.
