### ISSUE TITLE
Add general "mouse focus" event

### ISSUE THREAD

**Issue by bluemoehre** [folivoraAI/BetterTouchTool#841]
I am using the mouse buttons 3+4 (side) for emulating windows forward/backward navigation (CMD + Left/Right). But there is one disadvantage: the event it is always triggered on the active window - not the window, where the cursor is. So it would be great to trigger some kind of focus event to the hovered window first.

**Comment by rodalpho** [comment]
Under "trigger predefined action", "controlling other applications", "send shortcut to specific app", check "send to application under cursor". This should do what you want.

It's is really well hidden, and I didn't know about it until recently myself. The UI should be changed so it's more discoverable.

**Comment by bluemoehre** [comment]
Actually I cannot find that option =(

**Comment by tocker** [comment]
@rodalpho solution is great for general purpose. The problem is if you have two windows open of the same app, it will not switch to the window under the cursor.

To reproduce:
1. Create one of my favorite shortcut:

```
{
  "BTTTriggerType" : 21,
  "BTTTriggerTypeDescription" : "3 Finger Click",
  "BTTTriggerClass" : "BTTTriggerTypeMagicMouse",
  "BTTPredefinedActionType" : 128,
  "BTTPredefinedActionName" : "Send Shortcut to Specific App",
  "BTTShortcutApp" : "app under mouse cursor",
  "BTTShortcutSwitchToAppFirst" : "1",
  "BTTShortcutAppUnderCursor" : "app under mouse cursor",
  "BTTShortcutToSend" : "55,13",
  "BTTEnabled" : 1,
  "BTTOrder" : 6
}
```
(Sends ⌘w to the app).

2. Open two Chrome (works with other apps too)
3. 3-finger click on the window _not is focus_

**Expected result**: the tab under the cursor will close.
**Actual**: the tab in focus closes.

In addition, `send shortcut to specific app` works for shortcuts but not for mouse gestures.

`activate window under cursor` should be a separate action.

**Comment by bobodoll131** [comment]
It seems to me like BetterTouchTool has all the ingredients for auto-raise focus follows mouse. It can identify which app the cursor is hovering over (i.e. when moving windows without bringing them to front); it has a predefined action for activating window under cursor. But however much I try, I can't combine the two to automatically activate the window being hovered over. Would it be possible to combine the two into a single setting or option?
