### ISSUE TITLE
Change touch bar buttons based on active browser tab url

### ISSUE THREAD

**Issue by bakerac4** [folivoraAI/BetterTouchTool#874]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I'd like to be able to change the touch bar buttons depending on which url the active tab in my browser is pointing to.

i.e.
If I'm on a site like Jira - the touch bar would have create bug, close bug etc
If I'm on a site like GitHub - the touch bar would have Create Issue, View Pull Requests etc
but if Im on a site like Facebook it would have options for My Profile, My Feed etc.

Is this current possible? I can get the active tab's url via apple script, but I can't seem to find a way to change the buttons based on that url

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

**Comment by fifafu** [comment]
That's currently not possible but will be very soon!

Am 04.05.2017 um 14:51 schrieb Adam Baker <notifications@github.com>:

*IMPORTANT:* Don't post private requests here (e.g. license issues, etc.).
Please send me an email at boastr.net@gmail.com instead.
------------------------------
Description of bug/feature request/question:

I'd like to be able to change the touch bar buttons depending on which url
the active tab in my browser is pointing to.

i.e.
If I'm on a site like Jira - the touch bar would have create bug, close bug
etc
If I'm on a site like GitHub - the touch bar would have Create Issue, View
Pull Requests etc
but if Im on a site like Facebook it would have options for My Profile, My
Feed etc.

Is this current possible? I can get the active tab's url via apple script,
but I can't seem to find a way to change the buttons based on that url
Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch
Bar, etc.):

Touch Bar

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fifafu/BetterTouchTool/issues/874>, or mute the thread
