### ISSUE TITLE
assigning alt+tab to application switcher (predefined action) does not work as expected

### ISSUE THREAD

**Issue by dinovo1** [folivoraAI/BetterTouchTool#879]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
When assigning the keyboard shortcut alt+tab to perform the application switcher predefined task, the behavior is not as expected. expected behavior is to be able to hold down alt while repeatedly clicking tab to keep moving between apps in the switcher screen. What actually happens is that the first alt+tab combination brings up the switcher screen, but then when releasing tab and pressing it again the next application gets the focus and the task switcher closes, although I haven't released the alt key.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard.

#### Device information:

Type of Mac: macbook pro with touch bar
macOS version: Sierra
BetterTouchTool version: 2.10 (626) although the same thing happened with previous versions.

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by phidodido** [comment]
I have the same problem as described above. The application switcher does not work like when using command-tab.

**Comment by mikeweilgart** [comment]
This seems to be fixed with the new keyboard shortcuts implementation.

There are still a couple of downsides:

1. key repeat doesn't work the same - if you hold down alt-tab, nothing happens, whereas if you hold down the standard command-tab shortcut then the selector will travel across the open applications.
2. shift-tab doesn't work at all to go backwards in the list.  Pressing either shift key immediately exits the application switcher and switches to whichever application was highlighted at the time.

Still, it's very usable for just simple alt-tabbing, so I'm happy.  It would be nice to see these two minor drawbacks fixed but they're not bugs as bad as the one described above.
