### ISSUE TITLE
Window snapping does not take into account which monitor dock is currently located on

### ISSUE THREAD

**Issue by tbjerch** [folivoraAI/BetterTouchTool#968]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Window snapping on external monitor does not take into account where dock is (windows are always give size and location as if the dock is on the the Mac's built in screen).  

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
External monitor and Macbook Pro monitor 

#### Device information:

Type of Mac: Macbook Pro 13 inch, 2016
macOS version: 10.12.4
BetterTouchTool version: 2.11 (630)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
![external](https://cloud.githubusercontent.com/assets/9644487/26237355/1a657700-3c75-11e7-9b46-ff11cfc860a0.png)
<img width="1440" alt="built-in" src="https://cloud.githubusercontent.com/assets/9644487/26237359/1fd30aea-3c75-11e7-974f-b8c122b9b17e.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by RulerOf** [comment]
I'm experiencing the same problem.  Dock is on left-most monitor, but window snapping was behaving as though it's on the right-most monitor: snapping covers the full screen where the dock currently is, but leaves a gap on the screen where the dock most recently moved away from.

The problem usually eventually corrects itself, but I don't know how or why. Quick sequence of events:

* Moved the dock from left monitor to right monitor
* Moved dock back to left monitor a few seconds later
* I experienced the behavior reported above
* Opened BTT preferences via the menu bar icon
* Opened BTT advanced settings menu
* Went to **Window Snapping Settings** tab of Advanced Settings menu
* Closed BTT preferences
* Opened this site via menu bar icon -> user feedback -> report a bug
* Started writing this post, during the writing of it I discovered that the problem had corrected itself.

I experience this often enough that this is not the first time I've noticed it. I can only suggest that the behavior feels like BTT keeps track of the location of the dock by polling it every so often, instead of determining it when the snap occurs.

**Comment by fifafu** [comment]
Unfortunately this is a macOS issue. The APIs report the wrong screen frames after the dock is moved. I have opened an issue for this with Apple quite a while ago,but not yet received a reply. 

It was once fixed in a macOS beta, but came back again later.

**Comment by RulerOf** [comment]
@fifafu I've discovered that enabling and then disabling dock hiding seems to "update" Mac OS's sense of where the dock is and corrects the behavior seen in this issue.

It'd be a kludgey workaround, but perhaps that information could be of use to anyone who wants to look into this bug.
